### ISSUE TITLE
Clojure REPL not working if CLJX 0.5.0 & CLJS 2665 on classpath

### ISSUE THREAD

**Issue by postspectacular** [lynaghk/cljx#64]
Am not entirely sure if that is related to recent REPL changes in CLJS, but I can't open a Clojure REPL in my CLJX project anymore :( Removing all other deps and trying various recent  CLJS releases, the issue only seems to start w/ CLJS 0.0-2665, 2657 still is working fine...

```
lein repl
.... (a ton of various reflection warnings because I enabled them...)
Reflection warning, cemerick/piggieback.clj:54:3 - call to static method putProperty on org.mozilla.javascript.ScriptableObject can't be resolved (argument types: unknown, java.lang.String, java.lang.Object).
Error loading cljx.repl-middleware: java.lang.IllegalArgumentException: No single method: _setup of interface: cljs.repl.IJavaScriptEnv found for function: -setup of protocol: IJavaScriptEnv, compiling:(cemerick/piggieback.clj:149:5)
Exception in thread "main" java.lang.RuntimeException: Unable to resolve var: cljx.repl-middleware/wrap-cljx in this context, compiling:(/private/var/folders/x8/_j311xvx49151dw3t3gmcbmm0000gn/T/form-init601009934546686385.clj:1:1829)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6651)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3719)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.access$100(Compiler.java:38)
	at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6050)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.analyze(Compiler.java:6406)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5782)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5217)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3846)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6642)
	at clojure.lang.Compiler.analyze(Compiler.java:6445)
	at clojure.lang.Compiler.eval(Compiler.java:6700)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.eval(Compiler.java:6693)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: Unable to resolve var: cljx.repl-middleware/wrap-cljx in this context
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler$TheVarExpr$Parser.parse(Compiler.java:659)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
	... 34 more
```

**Comment by jvtrigueros** [comment]
This is a problem with [cemerick/piggieback](https://github.com/cemerick/piggieback/) and it's been already addressed. This project is using version 0.1.3 of piggieback, updating it to version 0.1.5 will fix these issues, although I don't know what side effects it may have.

I was able to get it working temporarily in my system by running the following commands:

```sh
cd <your-workspace>
git clone https://github.com/lynaghk/cljx.git
cd cljx
vim project.clj # change the version to something else
lein do pom, jar, install
```
Then you can go ahead and change the version on your local `project.clj` and it should pick up the changes.

I did this because I'm waiting on the repo owner to update the dependencies. As I'm just a newbie, I didn't want to submit a PR without knowing the full side effects.

**Comment by cemerick** [comment]
Yes, you need to upgrade ClojureScript and piggieback in unison. cljx will update its own piggieback dependency on the next release.
